run_mode:
  test: ""
  production: ""


storage_mode:
  local: 
    data:
      raw: "./data/raw/"
      clean: "./data/clean/"
    studies_uri: "sqlite:///./optuna_studies.db"
  cloud: 
    data:
      raw: ""
      clean: ""
    studies_uri: ""